export const billowJa: Record<string, string> = {
  "AI Chat Base Subscription Management Dashboard": "AIチャット型サブスクリプション管理ダッシュボード",
  "Originally built during a hackathon, the first version prioritized speed over structure, resulting in tightly coupled UI, state, and API logic that became difficult to debug and scale. Through rebuilding the project, I learned the importance of separation of concerns and restructured the application into a more maintainable and scalable AI dashboard.": "ハッカソンで制作した初期版は、構造より開発速度を優先したため、UI・状態管理・APIロジックが密接に結びつき、修正や拡張が難しい状態でした。この再開発を通して関心の分離の重要性を学び、保守しやすく拡張可能なAIダッシュボードへ再構築しました。",
  "Core Stacks": "使用技術",
  "Role": "役割",
  "UI Designer / Front-end Developer": "UIデザイナー / フロントエンド開発者",
  "Timeline": "期間",
  "One month, Apr-May, 2026ding": "1か月、2026年4月〜5月",
  "Overview": "概要",
  "Problem": "課題",
  "Approach": "アプローチ",
  "Reflection": "振り返り",
  "From Hackathon Prototype to Scalable Architecture": "ハッカソンの試作から、拡張可能な設計へ",
  "This project was originally developed during a hackathon in collaboration with a designer partner. Due to the speed-focused nature of the development, the initial implementation revealed limitations in structure and state management.": "このプロジェクトは、デザイナーと参加したハッカソンで制作したものです。短期間での完成を優先した結果、初期実装にはコード構成と状態管理の課題が残りました。",
  "I later revisited the project from both a design and architectural perspective. Rather than simply replicating the UI, I restructured the system around managing complex state and interactions, rebuilding it into a scalable front-end architecture.": "その後、デザインとアーキテクチャの両面からプロジェクトを見直しました。UIを再現するだけでなく、複雑な状態と操作を管理できるよう構成を整理し、拡張可能なフロントエンドへ再構築しました。",
  "Works, but Not Scalable": "動くものの、拡張できない構成",
  "In the hackathon version, the priority was to quickly deliver a working AI chat experience. As a result, UI rendering, state management, send logic, and API communication were all concentrated within a single component.": "ハッカソン版では、動作するAIチャットを短時間で完成させることを優先しました。その結果、UI表示、状態管理、送信処理、API通信が1つのコンポーネントに集中していました。",
  "Everything in One Component": "すべてを1つのコンポーネントで処理",
  "While this structure was sufficient for a prototype, the boundaries between responsibilities were unclear, and separation of concerns was lacking. API communication, local state, event handling, and UI rendering were tightly coupled, which made the code difficult to read, maintain, and scale.": "試作としては機能していましたが、各処理の責任範囲が曖昧で、関心を分離できていませんでした。API通信、ローカル状態、イベント処理、UI表示が密接に結びつき、コードの理解・保守・拡張が難しい構成でした。",
  "Simplified version of the original code ↓": "初期コードを簡略化した例 ↓",
  "Architecture Decision": "アーキテクチャの方針",
  "To make the chat feature scalable, I first defined clear responsibility boundaries for the architecture. Instead of separating code by file size or UI sections, I reorganized it by concern: View, Logic, Service, and State.": "チャット機能を拡張しやすくするため、まず各層の責任範囲を明確にしました。ファイルの大きさや画面単位ではなく、View、Logic、Service、Stateという役割ごとにコードを整理しました。",
  "Definition": "各レイヤーの役割",
  "Responsible for rendering the UI and layout, with no business logic": "ビジネスロジックを持たず、UIとレイアウトの表示を担当",
  "e.g. message list, chat input form, loading indicator": "例：メッセージ一覧、チャット入力フォーム、読み込み表示",
  "Manages chat flow, side effects, and user interactions": "チャットの流れ、副作用、ユーザー操作を管理",
  "e.g. handling message submission, managing loading state, triggering AI responses": "例：メッセージ送信、読み込み状態、AI応答の実行",
  "Encapsulates AI communication and external API calls": "AIとの通信や外部API呼び出しをまとめて管理",
  "e.g. calling AI API, formatting requests, parsing responses": "例：AI APIの呼び出し、リクエスト整形、レスポンス解析",
  "Manages shared conversation data across components": "複数のコンポーネントで共有する会話データを管理",
  "e.g. chat messages store, current chat room state, global state (Zustand)": "例：メッセージストア、現在のチャットルーム、グローバル状態（Zustand）",
  "View: Assembles and renders the UI": "View：UIを構成して表示する",
  "Logic: Controls message submission and side effects": "Logic：メッセージ送信と副作用を制御する",
  "Service: Abstracts AI communication": "Service：AIとの通信処理を切り離す",
  "State: Shares conversation data across components": "State：コンポーネント間で会話データを共有する",
  "As the feature evolved to support multiple chat rooms, conversation data needed to be shared beyond a single component. This made local state insufficient, so shared conversation data was moved into a centralized Zustand store.": "複数のチャットルームに対応するにつれ、会話データを1つのコンポーネントの外でも共有する必要が生まれました。ローカル状態だけでは管理が難しくなったため、共有データをZustandのストアへ移しました。",
  "Reevaluating the Development Process": "開発プロセスを見直して学んだこと",
  "When I was developing the application during the hackathon, I prioritized getting it up and running so much that I didn’t fully grasp the importance of structural design. As I revisited this project, my understanding of the importance of design, and my approach to AI changed significantly. Rather than simply letting AI create “something that sort of works,” I’ve started using it as a tool to assist my decision-making, guided by a clear design intent. While AI tools can quickly generate working code, I’ve come to realize that understanding the underlying architecture is essential for writing code that is maintainable, readable, and scalable. I’ve also come to find the process of designing while organizing the structure itself to be quite engaging.": "ハッカソンでは、まず動かすことを優先し、構造を設計する重要性を十分に理解できていませんでした。このプロジェクトを見直す中で、設計への理解とAIの使い方が大きく変わりました。AIに「とりあえず動くもの」を作らせるのではなく、明確な設計意図を持ち、判断を支える道具として使うようになりました。AIは短時間でコードを生成できますが、読みやすく保守・拡張できるコードを書くには、土台となるアーキテクチャを自分で理解する必要があります。構造を整理しながら設計すること自体の面白さも実感しました。",
  "The Gap Between Design and Implementation": "デザインと実装の間にある差",
  "This project also gave me an opportunity to reconsider the gap between design and implementation. Even when wireframes and style guides are well-organized in Figma, reproducing them accurately as a consistent UI requires careful implementation decisions. I was reminded that the process of bridging design and implementation cannot yet be fully automated; adjustments and judgments made by human eyes remain indispensable and continue to play a vital role. This project went beyond mere refactoring; it served as an opportunity to reevaluate how we utilize AI and how we translate design intent into implementation.": "このプロジェクトを通して、デザインと実装の間にある差についても考え直しました。Figmaでワイヤーフレームやスタイルガイドを整理しても、一貫したUIとして正確に再現するには、実装時の細かな判断が欠かせません。デザインと実装をつなぐ工程はまだ完全には自動化できず、人の目による調整と判断が重要だと改めて感じました。単なるリファクタリングにとどまらず、AIの活用方法と、デザイン意図を実装へ反映する方法を見直す機会になりました。",
  "Other Projects": "その他のプロジェクト",
};

export const billowJaMeta = {
  title: "Billow | AIチャットダッシュボード開発 | 近藤嵩成",
  description: "ハッカソンで制作したAIチャット型ダッシュボードを、関心の分離を軸に保守・拡張しやすい構成へ再設計したケーススタディです。",
};
