export const storeMapJa: Record<string, string> = {
  "Grocery Store Map Navigation": "店内商品ロケーター",
  "Why is finding a product in a supermarket still so difficult?": "海外のスーパーは広く、欲しい商品を見つけるのにかなりの労力を使います。",
  "Rethinking grocery shopping with interactive store maps and intuitive product discovery.": "そこで、私はバイト先の店内マップをもとにモバイルアプリを作り、買い物体験をデザインしました。",
  "Role": "役割",
  "UX Researcher / UI Designer / Frontend Developer": "UXリサーチャー / UIデザイナー / フロントエンド開発者",
  "Timeline": "期間",
  "One month, Jun - Jul, 2026": "1か月、2026年6月〜7月",
  "Overview": "概要",
  "Designing a seamless grocery shopping experience by combining product search with in-store navigation.": "探している商品の場所が、ひと目で分かるアプリを作成、テストしました。",
  "Less Wandering. More Shopping.": "探し回る時間を減らし、買い物をもっとスムーズに。",
  "Help shoppers in large supermarkets quickly find the products they need, reducing time spent wandering through unfamiliar aisles.": "大型スーパーで必要な商品をすばやく見つけられるようにし、慣れない売り場でも探し回る時間を減らします。",
  "Design × AI Tools × Development": "デザイン × AIツール × 開発",
  "Designed, built, and validated an interactive grocery navigation experience through user-centered design, AI-assisted workflows, and React Native development.": "ユーザー中心設計、AIを活用したワークフロー、React Native開発を通じて、インタラクティブな店内ナビゲーションを設計・実装・検証しました。",
  "Design Constraints": "デザインの制約",
  "Designed an additional Walmart app feature to gain experience working within an enterprise design system.": "独自のブランドデザインではなく、あえて「企業公式ブランドガイドを守る」というルールのもとでデザインしました。",
  "AI Assisted Workflow": "AIを活用したワークフロー",
  "Built an AI-assisted design-to-code workflow using Claude Code and Figma MCP.": "Claude CodeとFigma MCPを使い、AIを活用したデザインから実装までのワークフローを構築しました。",
  "Testing with a Coded Prototype": "実装したプロトタイプによるテスト",
  "Built a functional React Native prototype and conducted user testing to validate real-world interactions and usability.": "React Nativeで動作するプロトタイプを実装し、実環境で2種類のUIの操作性と使いやすさを検証しました。",
  "Context & Opportunity": "背景と機会",
  "A problem I witnessed every day while working at a supermarket": "スーパーマーケットで働く中で、毎日のように目にした課題",
  "While working at a supermarket, I frequently saw customers struggling to find products in large stores with thousands of items. Even when the products were available, many customers left without finding them, highlighting the need for a better in-store navigation experience.": "私はカナダの大手スーパーでアルバイトをした経験があり、何千もの商品が並ぶ広い店内で、目的の商品を見つけられず困っているお客様を何度も見ました。在庫があっても見つけられないまま帰ってしまうことも多く、商品の場所を簡単に確認できる仕組みが必要だと感じました。",
  "Customer side:": "お客様の声：",
  "“I spend too much time walking around the store.”": "「商品を見つけるのに時間がかかりすぎる」",
  "“I often have to ask staff where products are.”": "「商品の場所をスタッフに聞くことが多い」",
  "“Sometimes I leave without finding what I need.”": "「必要な商品を見つけられずに帰ることがある」",
  "“I forget what I came to buy.”": "「何を買いに来たのか忘れてしまう」",
  "Store Staff side:": "店舗スタッフの声：",
  "“Not every employee knows where every product is.”": "「従業員全員が商品の場所を把握しているわけではない」",
  "“Customers often interrupt us for directions.”": "「商品の場所を聞かれて作業が中断されることが多い」",
  "“Category signs alone aren’t enough.”": "「商品によっては案内看板だけでは十分ではない」",
  "“Product location data would make our jobs easier.”": "「商品の位置情報があれば業務が楽になる」",
  "Help shoppers find products quickly and confidently": "迷わず、すばやく商品を見つけられるようにする",
  "As a grocery shopper, I want to easily find the products I’m looking for, so that I can shop without getting lost.": "ユーザーストーリー : 買い物客として、店内で迷わず買い物できるよう、探している商品を簡単に見つけたい。",
  "Why Do Design Systems Matter?": "そもそもなぜデザインシステムが重要なのか？",
  "A design system is more than a collection of reusable components. It provides the shared language that allows new features to feel like a natural extension of an existing product.": "デザインシステムは、単なる再利用可能なコンポーネントの集まりではありません。新しい機能を既存のプロダクトへ自然になじませるための、共通のルールとして機能します。",
  "To explore this idea,": "この考えを検証するため、",
  "I intentionally designed a Store Map feature that doesn't exist in Walmart today.": "現在のWalmartには存在しない店内マップ機能を意図的にデザインしました。",
  "The challenge wasn't creating something new. It was creating something new that still \"felt like Walmart.\"": "課題は新しいものを作ることではなく、新しくても「Walmartらしい」と感じられるものを作ることでした。",
  "Only Walmart’s brand guidelines were publicly available.": "公開されていたのはWalmartのブランドガイドラインだけでした。",
  "The internal UI components, design tokens, and implementation details were not accessible. Instead of attempting to replicate the private design system, I focused on preserving the brand’s visual language while creating a scalable foundation for new components.": "開発で使われているUIコンポーネントやデザイントークンは非公開で、参照できたのは基本的なブランドガイドのみでした。そこで、公開情報からブランドの特徴を読み取り、Walmartらしさを保った新機能の設計に取り組みました。",
  "I translated the published brand principles into semantic design tokens.": "公開されているブランド原則をセマンティックトークンへ変換しました。",
  "Instead of applying brand colors directly to components, I introduced semantic tokens to make new UI patterns reusable and easier to maintain.": "Figma上ではブランドカラーをコンポーネントへ直接適用せず、セマンティックトークンを導入することで、新しいUIパターンを再利用かつ保守しやすくしました。",
  "The tokens powered reusable components across the feature.": "トークンを基盤に、機能全体で再利用可能なコンポーネントを構築しました。",
  "Using the token system, I built reusable components such as Item Pins and Item List Icons that were applied consistently throughout the Store Map experience. This allowed new interactions to feel native to Walmart’s existing visual language without copying its internal design system.": "作成したデザイントークンをもとに、商品ピンやリストアイコンなどのコンポーネントを設計し、店内マップ全体に一貫して適用しました。これにより、Walmartらしい見た目を保ちながら、新しい機能にも展開できるUIを構築しました。",
  "Implementing the Store Map": "店内マップの実装",
  "The goal was to help shoppers find products without getting lost in the store. Using the layout of the store where I work, I accurately recreated its aisles and product areas.": "店内で迷わず商品を見つけられるようにすることが目標でした。勤務先店舗のレイアウトをもとに、通路と商品エリアを正確に再現しました。",
  "To create a clean, structured SVG, I overlaid an 8 × 8 px grid on the original floor plan and traced each section cell by cell.": "整理されたSVGを作るため、元のフロアマップに8 × 8pxのグリッドを重ね、各エリアをセル単位でトレースしました。",
  "Streamlining Interactive Map Development with AI": "AIで商品情報と連動する店内マップの開発を効率化",
  "To make the map interactive, each area needed to be accurately connected to its product data. I introduced an AI-assisted workflow to streamline this repetitive process.": "マップ上に商品の場所を表示するには、各エリアと商品データを正確に紐づける必要があります。この繰り返し作業を効率化するため、AIを活用しました。",
  "Managing Hundreds of Cells Accurately": "数百以上の商品棚セルを正確に管理する",
  "Connecting products to their locations required a unique ID for every map element. Naming hundreds of elements manually would have been time-consuming and prone to errors or duplicates.": "商品と位置を紐づけるには、すべてのマップ要素に固有IDが必要でした。数百以上の要素を手作業で命名すると時間がかかり、ミスや重複も起こりやすくなります。",
  "Automating the Naming Process with Figma MCP and Claude": "Figma MCPとClaudeで命名作業を自動化",
  "I created a naming convention based on product category and location, then used Claude through Figma MCP to apply it to each layer. The layer names could then be used directly as SVG IDs, creating a smoother handoff to development.": "商品カテゴリーと位置に基づく命名規則を作り、Figma MCP経由でClaudeを使って各レイヤーへ適用しました。レイヤー名をそのままSVG IDとして利用でき、開発への受け渡しがスムーズになりました。",
  "Reduced Development Time and Improved Implementation Accuracy": "開発時間を短縮し、実装精度を向上",
  "The workflow reduced repetitive work and improved naming accuracy. It also made the transition from Figma to development more efficient.": "反復作業を減らし、命名の正確性を高めました。また、Figmaから開発への移行も効率化できました。",
  "Testing": "ユーザーテスト",
  "Balancing Map Visibility and Item Accessibility": "マップの見やすさと商品へのアクセスを両立する",
  "While navigating the store, shoppers need both a clear view of the map and quick access to their shopping list. However, maximizing one often compromises the other. To identify the better experience, I explored two navigation patterns and validated them through usability testing.": "店内を移動するとき、買い物客には見やすいマップと買い物リストへの素早いアクセスの両方が必要です。一方を優先すると、もう一方が損なわれがちです。よりよい体験を見極めるため、2つのナビゲーションパターンを検討し、ユーザビリティテストで検証しました。",
  "Comparing Two Navigation Patterns": "2つのナビゲーションパターンを比較",
  "Pattern A": "パターンA",
  "Header List": "ヘッダーリスト",
  "The Header List keeps shopping items constantly accessible, enabling faster switching between products while slightly reducing the visible map area.": "ヘッダーリストは商品へ常にアクセスでき、表示されるマップ領域を少し狭める代わりに、商品を素早く切り替えられます。",
  "Faster item switching": "商品をすばやく切り替えられる",
  "View the map and shopping list simultaneously": "マップと買い物リストを同時に確認できる",
  "Less map space": "マップの表示領域が狭い",
  "Pattern B": "パターンB",
  "Bottom Sheet": "ボトムシート",
  "The Bottom Sheet prioritizes map visibility by allowing the shopping list to be hidden when it’s not needed.": "ボトムシートは、不要なときに買い物リストを隠せるため、マップの見やすさを優先できます。",
  "Maximized map visibility": "マップを最大限に表示できる",
  "On-demand shopping list": "必要なときだけ買い物リストを表示できる",
  "Map is partially obscured when expanded": "展開時にマップの一部が隠れる",
  "Testing the Prototype in a Real Store": "実店舗でプロトタイプをテスト",
  "The participant was asked to locate six grocery items, switch between products, mark items as found, and navigate using the store map. During the sessions, I observed not only which interface participants preferred, but also how frequently they switched items, reopened the shopping list, and interacted with the map throughout the task.": "参加者には5つの商品を探し、商品を切り替え、見つけた商品を完了にし、店内マップを使って移動してもらいました。どちらのUIを好むかだけでなく、商品を切り替える頻度、買い物リストを開き直す頻度、タスク中のマップ操作も観察しました。",
  "Task: Find five products using Pattern A and five using Pattern B. Store Map.": "タスク：パターンAとパターンBを使って、それぞれ5つの商品を探す。",
  "Key Findings": "主な発見",
  "Users wanted to keep the map visible": "ユーザーはマップを表示したままにしたかった",
  "The Bottom Sheet covered too much of the map": "ボトムシートはマップを大きく隠してしまった",
  "Switching products felt easier from the header": "ヘッダーからの方が商品を切り替えやすかった",
  "Prioritizing a Smoother Shopping Flow": "よりスムーズな買い物の流れを優先",
  "Although the Bottom Sheet provided a larger map, participants switched between shopping items more frequently than they viewed the map in full screen. The Header List reduced unnecessary interactions, kept products readily accessible, and supported a smoother shopping experience. Based on these findings, it became the final interface.": "ボトムシートではマップを大きく表示できましたが、参加者はマップを全画面で見るよりも頻繁に商品を切り替えていました。ヘッダーリストは不要な操作を減らし、商品へすぐアクセスでき、よりスムーズな買い物を支えました。この結果から、最終UIにはヘッダーリストを採用しました。",
  "Reflection": "振り返り",
  "Design is the process of balancing constraints, trade-offs, and user needs.": "デザインとは、制約・トレードオフ・ユーザーのニーズのバランスを取るプロセスが必要不可欠である。",
  "This project taught me that the quality of a design is defined not by the number of possibilities, but by the ability to prioritize within constraints. By working through design constraints and trade-offs, I learned to evaluate decisions based not on visual novelty, but on reusability, implementation feasibility, and their impact on the user experience.": "このプロジェクトを通して、単純に見た目の良いデザインをつくることだけでなく、制約の中で何を優先するかを判断することが大切だと学びました。見た目の新しさだけでなく、再利用しやすいか、実装できるか、ユーザー体験を改善できるかという視点で考えるようになりました。",
  "I also realized that while AI has significantly accelerated the process of turning ideas into tangible solutions, speed alone has little value. What truly matters is using that extra time to validate assumptions, iterate on ideas, and make better-informed design decisions. This experience changed my understanding of efficient design. It is not about reducing effort. It is about spending more time on the decisions that create the greatest impact.": "また、AIによってアイデアを素早く形にできるようになっても、速さだけでは良いデザインにはならないと気づきました。AIで生まれた時間を、ユーザーと向き合う時間に使い、仮説の検証や改善をすることが求められると思います。つまり効率化によって単に作業を減らすことができる文、我々デザイナーは重要な意思決定により多くの時間を使うことだと学びました。",
  "Other Projects": "その他のプロジェクト",
};

export const storeMapJaMeta = {
  title: "店内マップ・ナビゲーション | 近藤嵩成",
  description: "商品検索と店内ナビゲーションを組み合わせた、スーパーマーケット向け店内マップのケーススタディです。",
};
