export const tastebudsJa: Record<string, string> = {
  "Overview": "概要",
  "Redevelopment": "再開発",
  "Reflection": "振り返り",
  "Role": "役割",
  "Timeline": "期間",
  "Rebuild:": "再開発：",
  "Web Developer / Web Designer": "Web開発者 / Webデザイナー",
  "Two months, Oct-Dec, 2025": "2か月、2025年10月〜12月",
  "Prototype": "プロトタイプ",
  "Live Site": "サイトを見る",
  "Other Projects": "その他のプロジェクト",
  "“TASTEBUDS” Food Blog — My Journey from JavaScript to React": "フードブログ「TASTEBUDS」— JavaScriptからReactへの学習記録",
  "Learning frontend fundamentals by rebuilding a food blog from vanilla JavaScript to React and Next.js.": "フードブログをVanilla JavaScriptからReact・Next.jsへ再構築しながら、フロントエンドの基礎を学びました。",
  "From Class Project to Rebuild": "授業プロジェクトから再開発へ",
  "TASTEBUDS began as a social media marketing project with my classmates, a food blog featuring restaurants and cafés in Vancouver.": "TASTEBUDSは、クラスメートと取り組んだソーシャルメディアマーケティングの課題として始まりました。バンクーバーのレストランやカフェを紹介するフードブログです。",
  "At first, I had not learned React yet, so I built the site using HTML, CSS (Sass), and vanilla JavaScript. As development progressed, I wanted a more efficient workflow, which led me to learn React and Next.js. I also redesigned the UI in Figma and rebuilt the project from the ground up.": "制作当初はReactを学ぶ前だったため、HTML、CSS（Sass）、Vanilla JavaScriptでサイトを構築しました。開発を進める中で、より効率的な制作方法を求めてReactとNext.jsを学びました。FigmaでUIも再設計し、プロジェクトを一から作り直しました。",
  "Built on Fundamentals": "基礎技術からの構築",
  "For the MVP, I built the project using fundamental web technologies. As I manually created blog cards with static HTML, I started to wonder, “Is there a more efficient way to replicate these?” This question led me to explore building a reusable structure using built-in browser features to dynamically generate content. This approach reduced repetition and improved scalability.": "MVPでは、Webの基礎技術を使ってプロジェクトを構築しました。静的HTMLでブログカードを一つずつ作る中で、「もっと効率よく複製できないか」と考えるようになりました。そこで、ブラウザ標準機能を使ってコンテンツを動的に生成する、再利用可能な仕組みを試しました。重複を減らし、拡張しやすい構成にできました。",
  "My approach": "実装アプローチ",
  "Using Vanilla JavaScript and the <template> element, I built a reusable card component.": "Vanilla JavaScriptと<template>要素を使い、再利用可能なカードコンポーネントを作成しました。",
  "Create a data structure for posts": "投稿データの構造を作成",
  "Use the <template> element": "<template>要素を使用",
  "Generate cards dynamically with JavaScript": "JavaScriptでカードを動的に生成",
  "Learning and Challenges": "学びと課題",
  "Through the MVP, I learned the basics of DOM manipulation, reusable UI design, and separating structure, data, and styles.": "MVPを通して、DOM操作、再利用可能なUI設計、構造・データ・スタイルを分離する基礎を学びました。",
  "At the same time, state management became complex, routing was hard to maintain, and the architecture didn’t scale well.": "一方で、状態管理が複雑になり、ルーティングの保守も難しく、拡張しにくい構成になりました。",
  "This led me to rebuild the project with Next.js.": "この課題をきっかけに、Next.jsでプロジェクトを再構築しました。",
  "Scaling the Architecture": "拡張可能なアーキテクチャへ",
  "To improve the scalability of the project, I redesigned the application using React and Next.js. The UI was rebuilt as React components, allowing the interface to be generated declaratively from data. I also introduced Next.js to better organize the page structure and implement routing for individual posts, resulting in a more maintainable and extensible architecture.": "プロジェクトの拡張性を高めるため、ReactとNext.jsを使ってアプリケーションを再設計しました。UIをReactコンポーネントとして再構築し、データから宣言的に画面を生成できるようにしました。さらにNext.jsでページ構成を整理し、投稿ごとのルーティングを実装することで、保守・拡張しやすいアーキテクチャに改善しました。",
  "Structured Content Management": "構造化されたコンテンツ管理",
  "In the MVP, blog content was stored as a front-end data array. While this worked for an early prototype, it required manual updates whenever a new post was added, which made content management less efficient as the project expanded.": "MVPでは、ブログコンテンツをフロントエンドのデータ配列として保存していました。初期の試作では機能しましたが、新しい投稿を追加するたびに手作業で更新する必要があり、規模が大きくなるにつれて管理効率が下がりました。",
  "This led me to rethink how post data should be handled. To create a more scalable structure, I separated content from the application code and migrated post management to Supabase.": "そこで投稿データの扱いを見直しました。より拡張しやすい構成にするため、コンテンツをアプリケーションコードから分離し、投稿管理をSupabaseへ移行しました。",
  "This made the workflow easier to maintain and created a foundation that could later evolve into a CMS-like system.": "これにより保守しやすいワークフローになり、将来的にCMSのような仕組みへ発展できる基盤を作れました。",
  "Design the post data structure": "投稿データの構造を設計",
  "Retrieve posts from Supabase": "Supabaseから投稿を取得",
  "Based on this structured data, UI components can dynamically generate blog cards and article pages.": "構造化したデータをもとに、UIコンポーネントからブログカードと記事ページを動的に生成できます。",
  "Rendering Architecture": "レンダリング設計",
  "The UI was rebuilt using reusable React components. Post data is passed into card components to generate article cards, creating a structure that can easily scale as more content is added.": "UIを再利用可能なReactコンポーネントで再構築しました。投稿データをカードコンポーネントへ渡して記事カードを生成し、コンテンツが増えても拡張しやすい構成にしました。",
  "PatternA: Curated layout for the homepage": "パターンA：トップページ用に選定したレイアウト",
  "To highlight the latest articles, the homepage selects specific posts from the dataset and displays them in a curated layout.": "最新記事を目立たせるため、トップページではデータから特定の投稿を選び、編集されたレイアウトで表示します。",
  "PatternB: Dynamic rendering for the blog archive": "パターンB：ブログ一覧の動的レンダリング",
  "On the blog page, filtered post data is mapped into card components to dynamically generate the article list.": "ブログページでは、絞り込んだ投稿データをカードコンポーネントへ割り当て、記事一覧を動的に生成します。",
  "Dynamic Routing": "動的ルーティング",
  "Previous Problem:": "以前の課題：",
  "In the MVP, each article was managed as a separate page, making the structure difficult to scale as content grew.": "MVPでは記事ごとに個別ページを管理していたため、コンテンツが増えるほど拡張が難しい構成でした。",
  "Solution:": "解決方法：",
  "I implemented Next.js Dynamic Routing using the /blog/[slug] route structure, allowing pages to be generated from a single shared template.": "Next.jsの動的ルーティングを/blog/[slug]の構成で実装し、1つの共通テンプレートからページを生成できるようにしました。",
  "Result:": "結果：",
  "By fetching content based on the slug, new articles can be added without creating new pages, improving scalability and maintainability.": "slugに応じてコンテンツを取得することで、新しいページを個別に作らず記事を追加でき、拡張性と保守性が向上しました。",
  "Learning Through Iteration": "試行錯誤を通した学び",
  "Through this project, I started from the fundamentals of JavaScript and continuously explored better ways to build features. I iterated through researching, experimenting, and refining my approach, and found the process of trial and error itself both engaging and rewarding as my understanding gradually deepened.": "このプロジェクトでは、JavaScriptの基礎から始め、より良い実装方法を継続的に探りました。調査、実験、改善を繰り返す中で理解が深まり、試行錯誤する過程そのものに面白さと手応えを感じました。",
  "Understanding the Limits of AI-Assisted Development": "AI支援開発の限界を理解する",
  "I also experimented with building admin and CMS-like features using AI. However, this experience made me realize that being able to implement functionality is not the same as fully understanding the underlying architecture. In parts of the CMS, multiple features ended up being combined into a single component, which made the structure harder to maintain and scale. This highlighted the importance of component design and separation of concerns.": "AIを使った管理画面やCMS機能の構築も試しました。しかし、機能を実装できることと、その土台となる設計を理解することは同じではないと気づきました。CMSの一部では複数の機能が1つのコンポーネントに集まり、保守・拡張しにくい構成になりました。この経験から、コンポーネント設計と関心の分離の重要性を学びました。",
  "Moving Forward": "今後に向けて",
  "Moving forward, I aim to deepen my understanding of architecture while using AI more intentionally, with the goal of building more scalable and maintainable systems.": "今後はAIを目的に応じて活用しながらアーキテクチャへの理解を深め、より拡張しやすく保守性の高いシステムを作ることを目指します。",
};

export const tastebudsJaMeta = {
  title: "Tastebuds | フードブログ再開発 | 近藤嵩成",
  description: "Vanilla JavaScriptで制作したフードブログをReact、Next.js、Supabaseで再構築した学習プロセスと設計改善のケーススタディです。",
};
