export const ukgJa: Record<string, string> = {
  "UKG Redesign Project": "UKG給与確認画面のリデザイン",
  "“How can I verify my work hours...?”": "「結局私の労働時間は正しいの？」",
  "The existing payroll screen showed total hours, but provided no way to verify them.": "既存の給与画面では合計勤務時間を確認できますが、その内訳を確かめる方法がありませんでした。",
  "Role": "役割",
  "UX Researcher / UI Designer / Front-end Developer": "UXリサーチャー / UIデザイナー / フロントエンド開発者",
  "Timeline": "期間",
  "One month, Apr-May, 2026": "1か月、2026年4月〜5月",
  "Overview": "概要",
  "Redesigning the payroll experience of \"UKG Pro\" to help employees understand and verify their payroll information.": "従業員が給与情報を理解し、自分で確認できるように、UKG Proの給与確認体験を再設計しました。",
  "An employee platform for managing work hours, accessing payroll information, and reviewing pay statements.": "勤務時間の管理、給与情報へのアクセス、給与明細の確認に使われる従業員向けプラットフォームです。",
  "The UKG main page I actually use": "実際に使用しているUKGのメイン画面",
  "Toward a More Transparent Payroll Experience": "給与の計算過程が分かる体験へ",
  "This project began with UX research focused on UKG Pro, which I actively use at my part-time workplace primarily to review pay statements.": "このプロジェクトは、アルバイト先で給与明細の確認に使用しているUKG ProへのUXリサーチから始まりました。",
  "The goal of the redesign was to improve transparency and verifiability within the payroll checking experience.": "給与情報の根拠を理解し、自分で確かめられる体験に改善することを目標としました。",
  "A User-Centered Design Process": "ユーザーを中心にしたデザインプロセス",
  "In this project, I first analyzed pain points through interviews and surveys conducted with real users, including my coworkers. Based on these insights, I designed the UI in Figma, built a prototype using AI-assisted development tools, and gathered feedback through participant evaluations.": "同僚を含む実際のユーザーへのインタビューとアンケートから課題を整理しました。その結果をもとにFigmaでUIを設計し、AIを活用してプロトタイプを開発した後、ユーザーテストでフィードバックを集めました。",
  "UX Research": "UXリサーチ",
  "UI design": "UIデザイン",
  "Prototype Development": "プロトタイプ開発",
  "User Feedback": "ユーザーフィードバック",
  "Research": "リサーチ",
  "A challenge uncovered through everyday conversations with coworkers": "同僚との日常会話から見つかった課題",
  "During a regular day at work, a conversation about checking payroll in UKG revealed a shared frustration among my coworkers and myself. To better understand the issue, I conducted interviews with other coworkers.": "勤務中にUKGで給与を確認する話をしたことから、私と同僚が同じ不満を抱えていると分かりました。課題を詳しく理解するため、ほかの同僚にもインタビューを行いました。",
  "“I can see the total hours worked, but I can’t see the breakdown.”": "「合計勤務時間は見られますが、内訳が分かりません」",
  "Grocery Staff": "売り場スタッフ",
  "“The punch records should exist somewhere, but I can’t verify them in UKG Pro. The schedule only shows assigned shifts.”": "「打刻記録はあるはずですが、UKG Proでは確認できません。スケジュールに表示されるのは予定されたシフトだけです」",
  "Cashier": "レジスタッフ",
  "Existing User Journey Pain Points": "既存の給与確認体験における課題",
  "Users cannot verify how payroll hours are calculated, forcing them to rely on manual estimation instead of system transparency.": "給与に使われた勤務時間の計算方法を確認できず、ユーザーは自分でおおよその時間を計算する必要がありました。",
  "Confirm that payroll hours were calculated accurately": "給与の勤務時間が正しく計算されているか確認する",
  "The user leaves without knowing the exact payroll calculation": "正確な計算方法が分からないまま確認を終える",
  "Research Findings": "リサーチ結果",
  "Main findings": "主な調査結果",
  "Conducted a survey to further validate existing pain points and identify strong user demand for better visibility into payroll records.": "既存の課題を検証し、給与記録をより詳しく確認したいというニーズを把握するため、アンケートを実施しました。",
  "80% of participants said they would not feel confident verifying payroll calculations if an error occurred.": "参加者の80％が、計算ミスがあった場合に給与を正しく確認できる自信がないと回答しました。",
  "90% of participants wanted access to actual clock-in and clock-out records.": "参加者の90％が、実際の出退勤記録を確認したいと回答しました。",
  "Users lacked confidence in payroll calculations because the system did not provide enough visibility into payroll records and actual worked hours.": "給与記録と実際の勤務時間が十分に表示されないため、ユーザーは給与計算に確信を持てていませんでした。",
  "Improve payroll transparency by providing visibility into clock-in and clock-out records.": "出退勤記録を確認できるようにし、給与計算の根拠を分かりやすくする。",
  "As an employee, I want to review my clock-in and clock-out history so that I can verify how my payroll hours were calculated.": "従業員として、給与の勤務時間がどのように計算されたか確認するため、出退勤履歴を見たい。",
  "UI Design": "UIデザイン",
  "Designing the UI Around UKG’s New Brand Identity": "UKGの新しいブランド表現に沿ったUI設計",
  "In 2025, UKG introduced a refreshed visual identity.": "2025年、UKGは新しいビジュアルアイデンティティを発表しました。",
  "The redesign explored how the updated visual identity could be applied more consistently across the payroll experience.": "このリデザインでは、新しいブランド表現を給与確認体験へ一貫して適用する方法を検討しました。",
  "Since the official design system was not publicly available, visual styles and UI patterns were independently analyzed from UKG’s public website.": "公式デザインシステムは公開されていなかったため、UKGの公開Webサイトから視覚表現とUIパターンを分析しました。",
  "Primitive color tokens derived from the analysis": "分析をもとに作成したプリミティブカラートークン",
  "Rather than connecting raw color values directly to the UI, I designed a hierarchical structure consisting of Primitive → Semantic → Component (optional). I placed particular emphasis on Semantic Tokens, as defining intent and meaning instead of visual values helps create more consistent design rules. Since this project contained relatively few repeated UI patterns, Component Tokens were introduced only where they provided additional value.": "色の値をUIへ直接指定せず、プリミティブ、セマンティック、コンポーネントの階層でトークンを設計しました。特に、色そのものではなく用途と意味を定義できるセマンティックトークンを重視しています。繰り返し使うUIパターンが少ないため、コンポーネントトークンは必要な箇所だけに導入しました。",
  "Using darker horizontal grid lines than vertical lines improves readability and makes time progression easier to scan.": "縦線より横線を濃くすることで、時間の流れを追いやすくしました。",
  "Emphasizing date numbers makes dates easier to identify at a glance.": "日付の数字を強調し、ひと目で確認しやすくしました。",
  "Representing clock-in records as a top-to-bottom timeline creates a clearer sense of chronological flow.": "出退勤記録を上から下へ進むタイムラインとして表示し、時系列を分かりやすくしました。",
  "Timeline colors and work cell variations improve visibility for attendance anomalies, including lateness and overtime.": "色とセルの表現を使い分け、遅刻や残業などの勤務状況を見つけやすくしました。",
  "Rapid prototyping with React and Codex.": "ReactとCodexによる迅速なプロトタイプ開発",
  "Rather than stopping at static Figma screens, I built a functional prototype in React to test the interaction model in a more realistic environment. Codex helped me move faster by supporting mock data setup and interaction implementation, making it possible to recreate a testable experience in a short timeframe.": "Figmaの静的な画面だけで終わらせず、より現実に近い操作を検証するため、Reactで動作するプロトタイプを開発しました。Codexを使ってモックデータと操作を実装し、短期間でテスト可能な体験を構築しました。",
  "I also translated the design tokens defined in Figma into CSS, creating a consistent workflow from design decisions to implementation.": "Figmaで定義したデザイントークンもCSSへ反映し、デザインから実装まで一貫したワークフローを構築しました。",
  "Did the redesign actually improve transparency?": "リデザインによって給与情報は分かりやすくなったか？",
  "To evaluate whether the redesign improved transparency during payroll verification, a comparative usability test was conducted comparing the existing UKG interface with the redesigned experience.": "給与確認時の分かりやすさが改善したかを評価するため、既存のUKG画面とリデザイン案を比較するユーザビリティテストを実施しました。",
  "Participants completed the same tasks based on a shared work scenario, while measuring their understanding of payroll information, trust, and confidence in verifying payroll accuracy.": "参加者には同じ勤務シナリオをもとにタスクを行ってもらい、給与情報への理解度、信頼度、正確性を確認する自信を測定しました。",
  "Comparative usability testing (Moderated)": "比較ユーザビリティテスト（モデレーターあり）",
  "UKG Pro users working at supermarkets": "スーパーマーケットで働くUKG Proユーザー",
  "5 participants": "5名",
  "Users became more confident verifying payroll information": "給与情報をより自信を持って確認できるようになった",
  "Participants using the redesigned version were able to verify payroll information with greater confidence compared to the existing interface.": "リデザイン版を使用した参加者は、既存画面よりも自信を持って給与情報を確認できました。",
  "Visibility of supporting information increased trust": "計算根拠の表示によって信頼度が向上した",
  "Trust scores improved from 3.8 to 6.8 after introducing supporting information such as worked hour breakdowns and clock-in/out records. These findings suggest that improving transparency increased trust in payroll information.": "勤務時間の内訳や出退勤記録を表示した結果、信頼度は3.8から6.8へ向上しました。給与計算の根拠を見せることが、給与情報への信頼につながると分かりました。",
  "Reflection": "振り返り",
  "Learning the Challenges of User-Centered Design": "ユーザー中心設計の難しさから学んだこと",
  "Through this project, I learned that user-centered design is not easy. Users are not all the same. At my workplace, people of different ages and backgrounds use the system, so my assumptions were not always correct. For example, the work hour cell UI was not as clear for everyone as I expected. At the same time, finding these problems showed me the value of talking to real users. This project taught me that UX design is not only about creating screens, but also about listening to users and testing ideas repeatedly.": "このプロジェクトを通して、ユーザー中心設計の難しさを学びました。職場では年齢や背景の異なる人が同じシステムを使うため、自分の想定がすべての人に当てはまるとは限りません。実際に、勤務時間セルのUIは期待したほど全員に分かりやすいものではありませんでした。一方で、この課題を発見できたことで、実際のユーザーと話し、繰り返し検証することの価値を実感しました。UXデザインは画面を作るだけでなく、ユーザーの声を聞きながら改善を続けることだと学びました。",
  "Other Projects": "その他のプロジェクト",
};

export const ukgJaMeta = {
  title: "給与確認アプリのリデザイン | 近藤嵩成",
  description: "ユーザー調査をもとにUKG Proの給与確認体験を再設計し、Reactで検証可能なプロトタイプを開発したケーススタディです。",
};
